image: node:12.14.1

stages:
  - compile
  - build
  - test
  - staging
  - production

cache:
  paths:
    - node_modules/

#--------- staging stage ---------#    
deploy-dev-server:
  stage: staging
  tags:
    - cd
    - native
    - ssh
  script:
    - echo $DEV_HOST
    - echo $DEV_USER
  only:
    - develop

#--------- production stage ---------#
deploy-production-server:
  stage: production
  tags:
    - cd
    - native
    - ssh
  script:
    - echo "deploy in production server"
  only:
    - master

    







