#
#--------------------------------------------------------------------------
# YAML Configuration
#--------------------------------------------------------------------------
#
# We are strictly implementing the Scaled Trunk-Based Development Branching Strategy in this project
# Please read the guidelines first before proceeding.
#
# For changes, please contact Karl Anthony Baluyot (karl@arbitrage.ph).
#

image: node:12.14.1

stages:
  - compile
  - build
  - test
  - staging
  - production

cache:
  paths:
    - node_modules/

#--------- compile stage ---------#    
install-dependencies:
  stage: compile
  tags:
    - ci
    - cd
    - node
    - docker
  before_script:
    - node --version
    - npm --version
  script:
    - npm install
  only:
    refs:
      - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "master"

#--------- build stage ---------#  
build-app:
  stage: build
  tags:
    - ci
    - cd
    - node
    - docker
  script:
    - npm run build
  only:
    refs:
      - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "master"

#--------- test stage ---------#    
run-lint:
  stage: test
  tags:
    - ci
    - cd
    - node
    - docker
  script:
    - echo "running lint"
  only:
    refs:
      - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "master"

run-unit-test:
  stage: test
  tags:
    - ci
    - cd
    - node
    - docker
  script:
    - echo "running unit test"
  only:
    refs:
      - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "master"

#--------- staging stage ---------#    
deploy-staging-server:
  stage: staging
  tags:
    - cd
    - native
    - ssh
  script:
    - ssh -t $DEV_USER@$DEV_HOST "whoami &&
      cd /var/www/html/dev-v2.arbitrage.ph && 
      git checkout master &&
      git pull origin master && 
      git checkout $CI_COMMIT_SHA &&
      npm install && 
      npm run build &&
      pm2 restart 0"
  environment:
    name: staging
    url: https://dev.lyduz.com
  only:
    - master
  except:
    - merge_requests
    - tags

#--------- production stage ---------#
deploy-production-server:
  stage: production
  tags:
    - cd
    - native
    - ssh
  script:
    - ssh -t $PROD_USER@$PROD_HOST "whoami &&
      cd /var/www/lyduz.com && 
      git checkout master &&
      git pull origin master && 
      git checkout $CI_COMMIT_SHA &&
      npm install && 
      npm run build &&
      pm2 restart 0"
  environment:
    name: production
    url: https://lyduz.com
  only:
    - /^release\/v[0-9]+(?:.[0-9]+)+$/
  except:
    - merge_requests
    - tags