image: node:12.14.1

stages:
  - compile
  - build
  - test
  - staging
  - production

cache:
  paths:
    - node_modules/

#--------- staging stage ---------#    
deploy-dev-server:
  stage: staging
  tags:
    - cd
    - native
    - ssh
  script:
    - ssh -t $DEV_USER@$DEV_HOST "whoami &&
      (echo $DEV_PASSWORD | sudo -S -su www-data bash -c 'binary-executor/binary-executor-linux-amd64 "--commands='whoami; 
      cd /var/www/html/dev-v2.arbitrage.ph; 
      git pull; 
      npm install; 
      npm run build;
      pm2 restart 1;
      '"')"
  only:
    - develop

#--------- production stage ---------#
deploy-production-server:
  stage: production
  tags:
    - cd
    - native
    - ssh
  script:
    - echo "deploy in production server"
  only:
    - master







